# Generated by scripts/codegen.py; do not edit.
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field, field_serializer, field_validator


class KeelModel(BaseModel):
    model_config = ConfigDict(extra='ignore')

    def model_dump(self, **kwargs):
        kwargs.setdefault('exclude_none', True)
        kwargs.setdefault('by_alias', True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs):
        kwargs.setdefault('exclude_none', True)
        kwargs.setdefault('by_alias', True)
        return super().model_dump_json(**kwargs)


class AuditEventEnvValue(str, Enum):
    DEV = 'dev'
    TEST = 'test'
    STAGING = 'staging'
    PROD = 'prod'


class AuditEventActionValue(str, Enum):
    INVOKE = 'invoke'
    TOOL_CALL = 'tool.call'
    SQL_EXECUTE = 'sql.execute'
    APPROVAL = 'approval'
    CONFIG_CHANGE = 'config.change'
    DATA_EXPORT = 'data.export'
    RUN_SUSPEND = 'run.suspend'
    RUN_RESUME = 'run.resume'
    AGENT_REGISTER = 'agent.register'
    RELEASE_GATE = 'release.gate'


class AuditEventRiskValue(str, Enum):
    LOW = 'low'
    MID = 'mid'
    HIGH = 'high'


class AuditEventDecisionValue(str, Enum):
    ALLOWED = 'allowed'
    DENIED = 'denied'
    PENDING = 'pending'
    APPROVED = 'approved'
    REJECTED = 'rejected'


class AuditEvent(KeelModel):
    event_id: str
    ts: datetime
    agent: str
    env: AuditEventEnvValue
    trace_id: Optional[str] = None
    run_id: Optional[str] = None
    actor: Optional[AuditEventActor] = None
    action: AuditEventActionValue
    resource: Optional[str] = None
    risk: AuditEventRiskValue
    decision: AuditEventDecisionValue
    approver: Optional[str] = None
    payload: Optional[dict[str, Any]] = None
    input_digest: Optional[str] = None
    prev_hash: Optional[str] = None
    hash: str

    @field_validator('ts')
    @classmethod
    def validate_ts(cls, value: datetime | None):
        if value is not None and value.tzinfo is None:
            raise ValueError('RFC 3339 timestamp requires timezone')
        return value

    @field_serializer('ts', when_used='json')
    def serialize_ts(self, value: datetime | None):
        if value is None:
            return None
        if value.tzinfo is None:
            raise ValueError('RFC 3339 timestamp requires timezone')
        return value.astimezone(timezone.utc).isoformat().replace('+00:00', 'Z')


class AuditEventActor(KeelModel):
    user_id: Optional[str] = None
    org_id: Optional[str] = None
    role: Optional[str] = None


for _model in (AuditEvent, AuditEventActor):
    _model.model_rebuild()
