# Generated by scripts/codegen.py; do not edit.
from enum import Enum

class ErrorCode(str, Enum):
    SERVER_INVALID_PARAM = 'SERVER_INVALID_PARAM'
    SERVER_NOT_FOUND = 'SERVER_NOT_FOUND'
    SERVER_INTERNAL_ERROR = 'SERVER_INTERNAL_ERROR'
    AGENT_MANIFEST_INVALID = 'AGENT_MANIFEST_INVALID'
    AGENT_SELF_CHECK_FAILED = 'AGENT_SELF_CHECK_FAILED'
    AGENT_NAME_TAKEN = 'AGENT_NAME_TAKEN'
    GW_QUOTA_EXCEEDED = 'GW_QUOTA_EXCEEDED'
    GW_CONCURRENCY_LIMIT = 'GW_CONCURRENCY_LIMIT'
    GW_AGENT_OFFLINE = 'GW_AGENT_OFFLINE'
    TOOL_NOT_GRANTED = 'TOOL_NOT_GRANTED'
    TOOL_RETIRED = 'TOOL_RETIRED'
    TOOL_TIMEOUT = 'TOOL_TIMEOUT'
    TOOL_HAS_PROD_DEPENDENTS = 'TOOL_HAS_PROD_DEPENDENTS'
    APPROVAL_REJECTED = 'APPROVAL_REJECTED'
    APPROVAL_EXPIRED = 'APPROVAL_EXPIRED'
    RUN_NOT_FOUND = 'RUN_NOT_FOUND'
    RUN_NOT_RESUMABLE = 'RUN_NOT_RESUMABLE'
    RUN_EXPIRED = 'RUN_EXPIRED'
    RUN_RESUME_DENIED = 'RUN_RESUME_DENIED'
    AUDIT_WRITE_FAILED = 'AUDIT_WRITE_FAILED'
    GUARD_INJECTION_BLOCKED = 'GUARD_INJECTION_BLOCKED'
    DELEGATE_NOT_DECLARED = 'DELEGATE_NOT_DECLARED'

    @property
    def retryable(self) -> bool:
        return _DETAILS[self][1]

    @property
    def http(self) -> int:
        return _DETAILS[self][2]

    @property
    def message(self) -> str:
        return _DETAILS[self][0]

_DETAILS = {
    ErrorCode.SERVER_INVALID_PARAM: ('请求参数不合法', False, 400),
    ErrorCode.SERVER_NOT_FOUND: ('资源不存在', False, 404),
    ErrorCode.SERVER_INTERNAL_ERROR: ('服务内部错误', True, 500),
    ErrorCode.AGENT_MANIFEST_INVALID: ('manifest 未通过校验', False, 400),
    ErrorCode.AGENT_SELF_CHECK_FAILED: ('注册自检未通过', False, 409),
    ErrorCode.AGENT_NAME_TAKEN: ('名称已被占用', False, 409),
    ErrorCode.GW_QUOTA_EXCEEDED: ('配额已用完', True, 429),
    ErrorCode.GW_CONCURRENCY_LIMIT: ('并发连接数达到上限', True, 429),
    ErrorCode.GW_AGENT_OFFLINE: ('智能体当前不可用', True, 503),
    ErrorCode.TOOL_NOT_GRANTED: ('智能体没有该工具的使用授权', False, 403),
    ErrorCode.TOOL_RETIRED: ('工具已下线', False, 410),
    ErrorCode.TOOL_TIMEOUT: ('工具调用超时', True, 504),
    ErrorCode.TOOL_HAS_PROD_DEPENDENTS: ('工具仍有 prod 依赖方，不能直接下线', False, 409),
    ErrorCode.APPROVAL_REJECTED: ('审批被驳回', False, 403),
    ErrorCode.APPROVAL_EXPIRED: ('审批超时未处理', False, 408),
    ErrorCode.RUN_NOT_FOUND: ('找不到该次执行', False, 404),
    ErrorCode.RUN_NOT_RESUMABLE: ('该次执行不处于可恢复状态', False, 409),
    ErrorCode.RUN_EXPIRED: ('该次执行已超过截止时间', False, 410),
    ErrorCode.RUN_RESUME_DENIED: ('无法恢复执行，凭据已失效', False, 401),
    ErrorCode.AUDIT_WRITE_FAILED: ('审计写入失败，操作已拒绝', True, 503),
    ErrorCode.GUARD_INJECTION_BLOCKED: ('输入被提示词注入检测拦截', False, 400),
    ErrorCode.DELEGATE_NOT_DECLARED: ('目标智能体未在 manifest 的 delegates 中声明', False, 403),
}
