# Generated by scripts/codegen.py; do not edit.
from enum import Enum

class ErrorCode(str, Enum):
    SERVER_INVALID_PARAM = 'SERVER_INVALID_PARAM'
    SERVER_NOT_FOUND = 'SERVER_NOT_FOUND'
    SERVER_INTERNAL_ERROR = 'SERVER_INTERNAL_ERROR'
    AGENT_MANIFEST_INVALID = 'AGENT_MANIFEST_INVALID'
    AGENT_SELF_CHECK_FAILED = 'AGENT_SELF_CHECK_FAILED'
    AGENT_NAME_TAKEN = 'AGENT_NAME_TAKEN'
    AGENT_NOT_RETIRED = 'AGENT_NOT_RETIRED'
    GW_QUOTA_EXCEEDED = 'GW_QUOTA_EXCEEDED'
    GW_CONCURRENCY_LIMIT = 'GW_CONCURRENCY_LIMIT'
    GW_AGENT_OFFLINE = 'GW_AGENT_OFFLINE'
    TOOL_NOT_GRANTED = 'TOOL_NOT_GRANTED'
    TOOL_RETIRED = 'TOOL_RETIRED'
    TOOL_TIMEOUT = 'TOOL_TIMEOUT'
    TOOL_HAS_PROD_DEPENDENTS = 'TOOL_HAS_PROD_DEPENDENTS'
    APPROVAL_REJECTED = 'APPROVAL_REJECTED'
    APPROVAL_EXPIRED = 'APPROVAL_EXPIRED'
    RUN_NOT_FOUND = 'RUN_NOT_FOUND'
    RUN_NOT_RESUMABLE = 'RUN_NOT_RESUMABLE'
    RUN_EXPIRED = 'RUN_EXPIRED'
    RUN_RESUME_DENIED = 'RUN_RESUME_DENIED'
    AUDIT_WRITE_FAILED = 'AUDIT_WRITE_FAILED'
    GUARD_INJECTION_BLOCKED = 'GUARD_INJECTION_BLOCKED'
    LLM_BUDGET_EXCEEDED = 'LLM_BUDGET_EXCEEDED'
    LLM_KEY_BLOCKED = 'LLM_KEY_BLOCKED'
    DELEGATE_NOT_DECLARED = 'DELEGATE_NOT_DECLARED'
    PROMPT_NOT_DECLARED = 'PROMPT_NOT_DECLARED'
    PROMPT_UNAVAILABLE = 'PROMPT_UNAVAILABLE'
    PROMPT_VARIABLE_MISSING = 'PROMPT_VARIABLE_MISSING'
    PROMPT_TYPE_MISMATCH = 'PROMPT_TYPE_MISMATCH'
    PROMPT_NOT_GATED = 'PROMPT_NOT_GATED'
    PROMPT_ROLLBACK_TARGET = 'PROMPT_ROLLBACK_TARGET'
    AUTH_UNAUTHENTICATED = 'AUTH_UNAUTHENTICATED'
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED'
    AUTH_TOKEN_AUDIENCE = 'AUTH_TOKEN_AUDIENCE'
    AUTH_CONSOLE_FORBIDDEN = 'AUTH_CONSOLE_FORBIDDEN'
    AUTH_PREVIEW_READONLY = 'AUTH_PREVIEW_READONLY'
    AUTH_BAD_CREDENTIALS = 'AUTH_BAD_CREDENTIALS'
    AUTH_CAPTCHA_REQUIRED = 'AUTH_CAPTCHA_REQUIRED'
    AUTH_LOCKED = 'AUTH_LOCKED'
    AUTH_SMS_RATE_LIMITED = 'AUTH_SMS_RATE_LIMITED'
    AUTH_GATEWAY_UNAVAILABLE = 'AUTH_GATEWAY_UNAVAILABLE'
    INSIGHT_UPSTREAM_UNAVAILABLE = 'INSIGHT_UPSTREAM_UNAVAILABLE'
    GIT_UPSTREAM_FAILED = 'GIT_UPSTREAM_FAILED'
    DEVFLOW_BUDGET_EXCEEDED = 'DEVFLOW_BUDGET_EXCEEDED'
    DEVFLOW_FIX_ROUNDS_EXHAUSTED = 'DEVFLOW_FIX_ROUNDS_EXHAUSTED'
    DEVFLOW_HOLDOUT_FAILED = 'DEVFLOW_HOLDOUT_FAILED'
    DEVFLOW_SANDBOX_TIMEOUT = 'DEVFLOW_SANDBOX_TIMEOUT'
    DEVFLOW_GRANT_MISSING = 'DEVFLOW_GRANT_MISSING'
    DEVFLOW_LINEAGE_FORBIDDEN = 'DEVFLOW_LINEAGE_FORBIDDEN'

    @property
    def retryable(self) -> bool:
        return _DETAILS[self][1]

    @property
    def http(self) -> int:
        return _DETAILS[self][2]

    @property
    def message(self) -> str:
        return _DETAILS[self][0]

_DETAILS = {
    ErrorCode.SERVER_INVALID_PARAM: ('请求参数不合法', False, 400),
    ErrorCode.SERVER_NOT_FOUND: ('资源不存在', False, 404),
    ErrorCode.SERVER_INTERNAL_ERROR: ('服务内部错误', True, 500),
    ErrorCode.AGENT_MANIFEST_INVALID: ('manifest 未通过校验', False, 400),
    ErrorCode.AGENT_SELF_CHECK_FAILED: ('注册自检未通过', False, 409),
    ErrorCode.AGENT_NAME_TAKEN: ('名称已被占用', False, 409),
    ErrorCode.AGENT_NOT_RETIRED: ('智能体还没下线，不能删除', False, 409),
    ErrorCode.GW_QUOTA_EXCEEDED: ('配额已用完', True, 429),
    ErrorCode.GW_CONCURRENCY_LIMIT: ('并发连接数达到上限', True, 429),
    ErrorCode.GW_AGENT_OFFLINE: ('智能体当前不可用', True, 503),
    ErrorCode.TOOL_NOT_GRANTED: ('智能体没有该工具的使用授权', False, 403),
    ErrorCode.TOOL_RETIRED: ('工具已下线', False, 410),
    ErrorCode.TOOL_TIMEOUT: ('工具调用超时', True, 504),
    ErrorCode.TOOL_HAS_PROD_DEPENDENTS: ('工具仍有 prod 依赖方，不能直接下线', False, 409),
    ErrorCode.APPROVAL_REJECTED: ('审批被驳回', False, 403),
    ErrorCode.APPROVAL_EXPIRED: ('审批超时未处理', False, 408),
    ErrorCode.RUN_NOT_FOUND: ('找不到该次执行', False, 404),
    ErrorCode.RUN_NOT_RESUMABLE: ('该次执行不处于可恢复状态', False, 409),
    ErrorCode.RUN_EXPIRED: ('该次执行已超过截止时间', False, 410),
    ErrorCode.RUN_RESUME_DENIED: ('无法恢复执行，凭据已失效', False, 401),
    ErrorCode.AUDIT_WRITE_FAILED: ('审计写入失败，操作已拒绝', True, 503),
    ErrorCode.GUARD_INJECTION_BLOCKED: ('输入被提示词注入检测拦截', False, 400),
    ErrorCode.LLM_BUDGET_EXCEEDED: ('模型日预算已用完', True, 429),
    ErrorCode.LLM_KEY_BLOCKED: ('虚拟 Key 已停用', False, 401),
    ErrorCode.DELEGATE_NOT_DECLARED: ('目标智能体未在 manifest 的 delegates 中声明', False, 403),
    ErrorCode.PROMPT_NOT_DECLARED: ('提示词未在 manifest 中声明', False, 404),
    ErrorCode.PROMPT_UNAVAILABLE: ('当前环境的提示词不可用', True, 503),
    ErrorCode.PROMPT_VARIABLE_MISSING: ('提示词变量缺失', False, 400),
    ErrorCode.PROMPT_TYPE_MISMATCH: ('提示词类型与声明不一致', False, 400),
    ErrorCode.PROMPT_NOT_GATED: ('提示词尚未通过 staging 回归，不能发布', False, 409),
    ErrorCode.PROMPT_ROLLBACK_TARGET: ('只能回滚到发布过的提示词版本', False, 409),
    ErrorCode.AUTH_UNAUTHENTICATED: ('请先登录后再继续', False, 401),
    ErrorCode.AUTH_TOKEN_EXPIRED: ('登录已过期，请重新登录', True, 401),
    ErrorCode.AUTH_TOKEN_AUDIENCE: ('这个登录态不能用于 Keel 控制台', False, 401),
    ErrorCode.AUTH_CONSOLE_FORBIDDEN: ('这个账号还没有开通控制台，请联系平台管理员', False, 403),
    ErrorCode.AUTH_PREVIEW_READONLY: ('预览模式只能查看，登录后才能操作', False, 403),
    ErrorCode.AUTH_BAD_CREDENTIALS: ('账号或密码不正确。没有账号或忘记密码，请联系平台管理员', False, 401),
    ErrorCode.AUTH_CAPTCHA_REQUIRED: ('为了保护账号，请填写图形验证码后再登录', False, 423),
    ErrorCode.AUTH_LOCKED: ('登录失败次数过多，请 15 分钟后再试', False, 423),
    ErrorCode.AUTH_SMS_RATE_LIMITED: ('操作太频繁，请稍后再试', True, 429),
    ErrorCode.AUTH_GATEWAY_UNAVAILABLE: ('登录服务暂时不可用，请稍后再试', True, 503),
    ErrorCode.INSIGHT_UPSTREAM_UNAVAILABLE: ('链路暂时拉不到，请稍后再试', True, 503),
    ErrorCode.GIT_UPSTREAM_FAILED: ('GitHub 调用失败', True, 502),
    ErrorCode.DEVFLOW_BUDGET_EXCEEDED: ('研发任务花费已达到预算上限', False, 409),
    ErrorCode.DEVFLOW_FIX_ROUNDS_EXHAUSTED: ('修复轮次已用完', False, 409),
    ErrorCode.DEVFLOW_HOLDOUT_FAILED: ('隐藏考题未通过门禁', False, 409),
    ErrorCode.DEVFLOW_SANDBOX_TIMEOUT: ('沙箱执行超过 10 分钟', True, 504),
    ErrorCode.DEVFLOW_GRANT_MISSING: ('缺少共享工具授权', False, 403),
    ErrorCode.DEVFLOW_LINEAGE_FORBIDDEN: ('不能向上生产，也不能修改自己', False, 403),
}
