# Generated by scripts/codegen.py; do not edit.
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field, field_serializer, field_validator


class KeelModel(BaseModel):
    model_config = ConfigDict(extra='ignore')

    def model_dump(self, **kwargs):
        kwargs.setdefault('exclude_none', True)
        kwargs.setdefault('by_alias', True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs):
        kwargs.setdefault('exclude_none', True)
        kwargs.setdefault('by_alias', True)
        return super().model_dump_json(**kwargs)


class StepEventStatusValue(str, Enum):
    OK = 'ok'
    FALLBACK = 'fallback'
    FAILED = 'failed'


class ToolEventStatusValue(str, Enum):
    OK = 'ok'
    FALLBACK = 'fallback'
    FAILED = 'failed'


class SuspendEventReasonValue(str, Enum):
    APPROVAL = 'approval'
    INPUT_REQUIRED = 'input_required'
    HANDOFF = 'handoff'


class StepEvent(KeelModel):
    name: str
    status: StepEventStatusValue


class ToolEvent(KeelModel):
    name: str
    status: ToolEventStatusValue


class TokenEvent(KeelModel):
    text: str


class FinalEvent(KeelModel):
    answer: str
    citations: Optional[list[dict[str, Any]]] = None
    meta: Optional[dict[str, Any]] = None
    trace_id: str
    run_id: str


class ErrorEvent(KeelModel):
    code: str
    message: str
    trace_id: str
    run_id: str
    retryable: bool


class SuspendEvent(KeelModel):
    run_id: str
    reason: SuspendEventReasonValue
    ref: Optional[str] = None
    prompt: Optional[str] = None
    deadline: Optional[datetime] = None
    resume_token: str
    trace_id: str

    @field_validator('deadline')
    @classmethod
    def validate_deadline(cls, value: datetime | None):
        if value is not None and value.tzinfo is None:
            raise ValueError('RFC 3339 timestamp requires timezone')
        return value

    @field_serializer('deadline', when_used='json')
    def serialize_deadline(self, value: datetime | None):
        if value is None:
            return None
        if value.tzinfo is None:
            raise ValueError('RFC 3339 timestamp requires timezone')
        return value.astimezone(timezone.utc).isoformat().replace('+00:00', 'Z')


for _model in (StepEvent, ToolEvent, TokenEvent, FinalEvent, ErrorEvent, SuspendEvent):
    _model.model_rebuild()
