# Generated by scripts/codegen.py; do not edit.
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field, field_serializer, field_validator


class KeelModel(BaseModel):
    model_config = ConfigDict(extra='ignore')

    def model_dump(self, **kwargs):
        kwargs.setdefault('exclude_none', True)
        kwargs.setdefault('by_alias', True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs):
        kwargs.setdefault('exclude_none', True)
        kwargs.setdefault('by_alias', True)
        return super().model_dump_json(**kwargs)


class AgentManifestApiVersionValue(str, Enum):
    KEEL_V1 = 'keel/v1'


class AgentManifestKindValue(str, Enum):
    AGENT = 'Agent'
    SERVICE = 'Service'


class AgentManifestSpecRuntimeTypeValue(str, Enum):
    CODE = 'code'
    DIFY = 'dify'


class AgentManifestSpecRuntimeLanguageValue(str, Enum):
    PYTHON = 'python'
    JAVA = 'java'
    OTHER = 'other'


class AgentManifestSpecRuntimeLivenessValue(str, Enum):
    K8S = 'k8s'
    HEARTBEAT = 'heartbeat'
    PROBE = 'probe'


class AgentManifestSpecToolsItemAccessValue(str, Enum):
    READ = 'read'
    WRITE = 'write'
    EXEC = 'exec'


class AgentManifestSpecToolsItemRiskValue(str, Enum):
    LOW = 'low'
    MID = 'mid'
    HIGH = 'high'


class AgentManifestSpecToolsItemApprovalValue(str, Enum):
    REQUIRED = 'required'
    NONE = 'none'


class AgentManifestSpecGuardrailsInputInjectionValue(str, Enum):
    OFF = 'off'
    SHADOW = 'shadow'
    ENFORCE = 'enforce'


class AgentManifestSpecGuardrailsGroundingValue(str, Enum):
    OFF = 'off'
    SHADOW = 'shadow'
    ENFORCE = 'enforce'


class AgentManifestSpecGuardrailsPiiValue(str, Enum):
    OFF = 'off'
    MASK = 'mask'


class AgentManifestSpecPromptsSourceValue(str, Enum):
    LANGFUSE = 'langfuse'
    LOCAL = 'local'


class AgentManifestSpecPromptsItemsItemTypeValue(str, Enum):
    TEXT = 'text'
    CHAT = 'chat'


class AgentManifest(KeelModel):
    apiVersion: AgentManifestApiVersionValue
    kind: Optional[AgentManifestKindValue] = None
    metadata: AgentManifestMetadata
    spec: AgentManifestSpec


class AgentManifestMetadata(KeelModel):
    name: str
    displayName: Optional[str] = None
    owner: Optional[str] = None


class AgentManifestSpec(KeelModel):
    runtime: AgentManifestSpecRuntime
    auth: Optional[AgentManifestSpecAuth] = None
    knowledge: Optional[list[AgentManifestSpecKnowledgeItem]] = None
    tools: Optional[list[AgentManifestSpecToolsItem]] = None
    delegates: Optional[list[str]] = None
    guardrails: Optional[AgentManifestSpecGuardrails] = None
    audit: Optional[AgentManifestSpecAudit] = None
    prompts: Optional[AgentManifestSpecPrompts] = None
    models: Optional[AgentManifestSpecModels] = None
    eval: Optional[AgentManifestSpecEval] = None
    quality: Optional[AgentManifestSpecQuality] = None


class AgentManifestSpecRuntime(KeelModel):
    type: Optional[AgentManifestSpecRuntimeTypeValue] = None
    language: Optional[AgentManifestSpecRuntimeLanguageValue] = None
    endpoint: str
    liveness: Optional[AgentManifestSpecRuntimeLivenessValue] = None


class AgentManifestSpecAuth(KeelModel):
    audience: Optional[str] = None
    roles: Optional[list[str]] = None


class AgentManifestSpecKnowledgeItem(KeelModel):
    kb: str


class AgentManifestSpecToolsItem(KeelModel):
    name: str
    access: Optional[AgentManifestSpecToolsItemAccessValue] = None
    risk: Optional[AgentManifestSpecToolsItemRiskValue] = None
    approval: Optional[AgentManifestSpecToolsItemApprovalValue] = None


class AgentManifestSpecGuardrails(KeelModel):
    inputInjection: Optional[AgentManifestSpecGuardrailsInputInjectionValue] = None
    grounding: Optional[AgentManifestSpecGuardrailsGroundingValue] = None
    pii: Optional[AgentManifestSpecGuardrailsPiiValue] = None


class AgentManifestSpecAudit(KeelModel):
    retentionDays: Optional[int] = None
    captureFields: Optional[list[str]] = None


class AgentManifestSpecPrompts(KeelModel):
    source: Optional[AgentManifestSpecPromptsSourceValue] = None
    label: Optional[str] = None
    items: Optional[list[AgentManifestSpecPromptsItemsItem]] = None


class AgentManifestSpecModels(KeelModel):
    default_: Optional[str] = Field(default=None, alias='default')
    fallback: Optional[list[str]] = None
    budget: Optional[AgentManifestSpecModelsBudget] = None
    byPurpose: Optional[AgentManifestSpecModelsByPurpose] = None


class AgentManifestSpecEval(KeelModel):
    dataset: Optional[str] = None
    evaluators: Optional[list[str]] = None
    gate: Optional[AgentManifestSpecEvalGate] = None


class AgentManifestSpecQuality(KeelModel):
    onlineEvalSampling: Optional[float] = None
    feedback: Optional[bool] = None
    annotationQueue: Optional[str] = None


class AgentManifestSpecPromptsItemsItem(KeelModel):
    name: str
    type: AgentManifestSpecPromptsItemsItemTypeValue


class AgentManifestSpecModelsBudget(KeelModel):
    dailyCny: Optional[float] = None
    maxSteps: Optional[int] = None


class AgentManifestSpecModelsByPurpose(KeelModel):
    rewrite: Optional[AgentManifestSpecModelsByPurposeRewrite] = None
    judge: Optional[AgentManifestSpecModelsByPurposeJudge] = None
    answer: Optional[AgentManifestSpecModelsByPurposeAnswer] = None
    embedding: Optional[AgentManifestSpecModelsByPurposeEmbedding] = None


class AgentManifestSpecEvalGate(KeelModel):
    minScore: Optional[float] = None
    maxRegression: Optional[float] = None
    byTag: Optional[bool] = None


class AgentManifestSpecModelsByPurposeRewrite(KeelModel):
    default_: Optional[str] = Field(default=None, alias='default')
    fallback: Optional[list[str]] = None


class AgentManifestSpecModelsByPurposeJudge(KeelModel):
    default_: Optional[str] = Field(default=None, alias='default')
    fallback: Optional[list[str]] = None


class AgentManifestSpecModelsByPurposeAnswer(KeelModel):
    default_: Optional[str] = Field(default=None, alias='default')
    fallback: Optional[list[str]] = None


class AgentManifestSpecModelsByPurposeEmbedding(KeelModel):
    fallback: Optional[list[str]] = None
    default_: Optional[str] = Field(default=None, alias='default')


for _model in (AgentManifest, AgentManifestMetadata, AgentManifestSpec, AgentManifestSpecRuntime, AgentManifestSpecAuth, AgentManifestSpecKnowledgeItem, AgentManifestSpecToolsItem, AgentManifestSpecGuardrails, AgentManifestSpecAudit, AgentManifestSpecPrompts, AgentManifestSpecModels, AgentManifestSpecEval, AgentManifestSpecQuality, AgentManifestSpecPromptsItemsItem, AgentManifestSpecModelsBudget, AgentManifestSpecModelsByPurpose, AgentManifestSpecEvalGate, AgentManifestSpecModelsByPurposeRewrite, AgentManifestSpecModelsByPurposeJudge, AgentManifestSpecModelsByPurposeAnswer, AgentManifestSpecModelsByPurposeEmbedding):
    _model.model_rebuild()
