// Generated by scripts/codegen.py; do not edit.
package com.keel.common.model;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import java.time.Instant;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record AgentManifest(
    @JsonProperty("apiVersion") AgentManifestApiVersionValue apiVersion,
    @JsonProperty("kind") AgentManifestKindValue kind,
    @JsonProperty("metadata") AgentManifestMetadata metadata,
    @JsonProperty("spec") AgentManifestSpec spec
) {
    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestMetadata(
        @JsonProperty("name") String name,
        @JsonProperty("displayName") String displayName,
        @JsonProperty("owner") String owner
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpec(
        @JsonProperty("runtime") AgentManifestSpecRuntime runtime,
        @JsonProperty("auth") AgentManifestSpecAuth auth,
        @JsonProperty("knowledge") List<AgentManifestSpecKnowledgeItem> knowledge,
        @JsonProperty("tools") List<AgentManifestSpecToolsItem> tools,
        @JsonProperty("delegates") List<String> delegates,
        @JsonProperty("guardrails") AgentManifestSpecGuardrails guardrails,
        @JsonProperty("audit") AgentManifestSpecAudit audit,
        @JsonProperty("prompts") AgentManifestSpecPrompts prompts,
        @JsonProperty("models") AgentManifestSpecModels models,
        @JsonProperty("eval") AgentManifestSpecEval eval,
        @JsonProperty("quality") AgentManifestSpecQuality quality
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecRuntime(
        @JsonProperty("type") AgentManifestSpecRuntimeTypeValue type,
        @JsonProperty("language") AgentManifestSpecRuntimeLanguageValue language,
        @JsonProperty("endpoint") String endpoint,
        @JsonProperty("liveness") AgentManifestSpecRuntimeLivenessValue liveness
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecAuth(
        @JsonProperty("audience") String audience,
        @JsonProperty("roles") List<String> roles
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecKnowledgeItem(
        @JsonProperty("kb") String kb
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecToolsItem(
        @JsonProperty("name") String name,
        @JsonProperty("access") AgentManifestSpecToolsItemAccessValue access,
        @JsonProperty("risk") AgentManifestSpecToolsItemRiskValue risk,
        @JsonProperty("approval") AgentManifestSpecToolsItemApprovalValue approval
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecGuardrails(
        @JsonProperty("inputInjection") AgentManifestSpecGuardrailsInputInjectionValue inputInjection,
        @JsonProperty("grounding") AgentManifestSpecGuardrailsGroundingValue grounding,
        @JsonProperty("pii") AgentManifestSpecGuardrailsPiiValue pii
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecAudit(
        @JsonProperty("retentionDays") Integer retentionDays,
        @JsonProperty("captureFields") List<String> captureFields
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecPrompts(
        @JsonProperty("source") AgentManifestSpecPromptsSourceValue source,
        @JsonProperty("label") String label,
        @JsonProperty("items") List<AgentManifestSpecPromptsItemsItem> items
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecModels(
        @JsonProperty("default") String default_,
        @JsonProperty("fallback") List<String> fallback,
        @JsonProperty("budget") AgentManifestSpecModelsBudget budget,
        @JsonProperty("byPurpose") AgentManifestSpecModelsByPurpose byPurpose
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecEval(
        @JsonProperty("dataset") String dataset,
        @JsonProperty("evaluators") List<String> evaluators,
        @JsonProperty("gate") AgentManifestSpecEvalGate gate
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecQuality(
        @JsonProperty("onlineEvalSampling") Double onlineEvalSampling,
        @JsonProperty("feedback") Boolean feedback,
        @JsonProperty("annotationQueue") String annotationQueue
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecPromptsItemsItem(
        @JsonProperty("name") String name,
        @JsonProperty("type") AgentManifestSpecPromptsItemsItemTypeValue type
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecModelsBudget(
        @JsonProperty("dailyCny") Double dailyCny,
        @JsonProperty("maxSteps") Integer maxSteps
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecModelsByPurpose(
        @JsonProperty("rewrite") AgentManifestSpecModelsByPurposeRewrite rewrite,
        @JsonProperty("judge") AgentManifestSpecModelsByPurposeJudge judge,
        @JsonProperty("answer") AgentManifestSpecModelsByPurposeAnswer answer,
        @JsonProperty("embedding") AgentManifestSpecModelsByPurposeEmbedding embedding
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecEvalGate(
        @JsonProperty("minScore") Double minScore,
        @JsonProperty("maxRegression") Double maxRegression,
        @JsonProperty("byTag") Boolean byTag
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecModelsByPurposeRewrite(
        @JsonProperty("default") String default_,
        @JsonProperty("fallback") List<String> fallback
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecModelsByPurposeJudge(
        @JsonProperty("default") String default_,
        @JsonProperty("fallback") List<String> fallback
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecModelsByPurposeAnswer(
        @JsonProperty("default") String default_,
        @JsonProperty("fallback") List<String> fallback
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AgentManifestSpecModelsByPurposeEmbedding(
        @JsonProperty("fallback") List<String> fallback,
        @JsonProperty("default") String default_
    ) {}

    public enum AgentManifestApiVersionValue {
        KEEL_V1("keel/v1");
        private final String value;
        AgentManifestApiVersionValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestApiVersionValue fromValue(String value) {
            for (AgentManifestApiVersionValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AgentManifestKindValue {
        AGENT("Agent"), SERVICE("Service");
        private final String value;
        AgentManifestKindValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestKindValue fromValue(String value) {
            for (AgentManifestKindValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AgentManifestSpecRuntimeTypeValue {
        CODE("code"), DIFY("dify");
        private final String value;
        AgentManifestSpecRuntimeTypeValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestSpecRuntimeTypeValue fromValue(String value) {
            for (AgentManifestSpecRuntimeTypeValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AgentManifestSpecRuntimeLanguageValue {
        PYTHON("python"), JAVA("java"), OTHER("other");
        private final String value;
        AgentManifestSpecRuntimeLanguageValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestSpecRuntimeLanguageValue fromValue(String value) {
            for (AgentManifestSpecRuntimeLanguageValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AgentManifestSpecRuntimeLivenessValue {
        K8S("k8s"), HEARTBEAT("heartbeat"), PROBE("probe");
        private final String value;
        AgentManifestSpecRuntimeLivenessValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestSpecRuntimeLivenessValue fromValue(String value) {
            for (AgentManifestSpecRuntimeLivenessValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AgentManifestSpecToolsItemAccessValue {
        READ("read"), WRITE("write"), EXEC("exec");
        private final String value;
        AgentManifestSpecToolsItemAccessValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestSpecToolsItemAccessValue fromValue(String value) {
            for (AgentManifestSpecToolsItemAccessValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AgentManifestSpecToolsItemRiskValue {
        LOW("low"), MID("mid"), HIGH("high");
        private final String value;
        AgentManifestSpecToolsItemRiskValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestSpecToolsItemRiskValue fromValue(String value) {
            for (AgentManifestSpecToolsItemRiskValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AgentManifestSpecToolsItemApprovalValue {
        REQUIRED("required"), NONE("none");
        private final String value;
        AgentManifestSpecToolsItemApprovalValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestSpecToolsItemApprovalValue fromValue(String value) {
            for (AgentManifestSpecToolsItemApprovalValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AgentManifestSpecGuardrailsInputInjectionValue {
        OFF("off"), SHADOW("shadow"), ENFORCE("enforce");
        private final String value;
        AgentManifestSpecGuardrailsInputInjectionValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestSpecGuardrailsInputInjectionValue fromValue(String value) {
            for (AgentManifestSpecGuardrailsInputInjectionValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AgentManifestSpecGuardrailsGroundingValue {
        OFF("off"), SHADOW("shadow"), ENFORCE("enforce");
        private final String value;
        AgentManifestSpecGuardrailsGroundingValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestSpecGuardrailsGroundingValue fromValue(String value) {
            for (AgentManifestSpecGuardrailsGroundingValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AgentManifestSpecGuardrailsPiiValue {
        OFF("off"), MASK("mask");
        private final String value;
        AgentManifestSpecGuardrailsPiiValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestSpecGuardrailsPiiValue fromValue(String value) {
            for (AgentManifestSpecGuardrailsPiiValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AgentManifestSpecPromptsSourceValue {
        LANGFUSE("langfuse"), LOCAL("local");
        private final String value;
        AgentManifestSpecPromptsSourceValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestSpecPromptsSourceValue fromValue(String value) {
            for (AgentManifestSpecPromptsSourceValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AgentManifestSpecPromptsItemsItemTypeValue {
        TEXT("text"), CHAT("chat");
        private final String value;
        AgentManifestSpecPromptsItemsItemTypeValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AgentManifestSpecPromptsItemsItemTypeValue fromValue(String value) {
            for (AgentManifestSpecPromptsItemsItemTypeValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

}
