// Generated by scripts/codegen.py; do not edit.
package com.keel.common.model;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import java.time.Instant;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record AuditEvent(
    @JsonProperty("event_id") String event_id,
    @JsonSerialize(using = ToStringSerializer.class) @JsonProperty("ts") Instant ts,
    @JsonProperty("agent") String agent,
    @JsonProperty("env") AuditEventEnvValue env,
    @JsonProperty("trace_id") String trace_id,
    @JsonProperty("run_id") String run_id,
    @JsonProperty("actor") AuditEventActor actor,
    @JsonProperty("action") AuditEventActionValue action,
    @JsonProperty("resource") String resource,
    @JsonProperty("risk") AuditEventRiskValue risk,
    @JsonProperty("decision") AuditEventDecisionValue decision,
    @JsonProperty("approver") String approver,
    @JsonProperty("payload") Map<String, Object> payload,
    @JsonProperty("input_digest") String input_digest,
    @JsonProperty("prev_hash") String prev_hash,
    @JsonProperty("hash") String hash
) {
    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record AuditEventActor(
        @JsonProperty("user_id") String user_id,
        @JsonProperty("org_id") String org_id,
        @JsonProperty("role") String role
    ) {}

    public enum AuditEventEnvValue {
        DEV("dev"), STAGING("staging"), PROD("prod");
        private final String value;
        AuditEventEnvValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AuditEventEnvValue fromValue(String value) {
            for (AuditEventEnvValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AuditEventActionValue {
        INVOKE("invoke"), TOOL_CALL("tool.call"), SQL_EXECUTE("sql.execute"), APPROVAL("approval"), CONFIG_CHANGE("config.change"), DATA_EXPORT("data.export"), RUN_SUSPEND("run.suspend"), RUN_RESUME("run.resume"), AGENT_REGISTER("agent.register"), RELEASE_GATE("release.gate");
        private final String value;
        AuditEventActionValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AuditEventActionValue fromValue(String value) {
            for (AuditEventActionValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AuditEventRiskValue {
        LOW("low"), MID("mid"), HIGH("high");
        private final String value;
        AuditEventRiskValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AuditEventRiskValue fromValue(String value) {
            for (AuditEventRiskValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

    public enum AuditEventDecisionValue {
        ALLOWED("allowed"), DENIED("denied"), PENDING("pending"), APPROVED("approved"), REJECTED("rejected");
        private final String value;
        AuditEventDecisionValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static AuditEventDecisionValue fromValue(String value) {
            for (AuditEventDecisionValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

}
