// Generated by scripts/codegen.py; do not edit.
package com.keel.common.model;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import java.time.Instant;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ErrorEvent(
    @JsonProperty("code") String code,
    @JsonProperty("message") String message,
    @JsonProperty("trace_id") String trace_id,
    @JsonProperty("run_id") String run_id,
    @JsonProperty("retryable") Boolean retryable
) {
}
