// Generated by scripts/codegen.py; do not edit.
package com.keel.common.model;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import java.time.Instant;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record FinalEvent(
    @JsonProperty("answer") String answer,
    @JsonProperty("citations") List<Map<String, Object>> citations,
    @JsonProperty("meta") Map<String, Object> meta,
    @JsonProperty("trace_id") String trace_id,
    @JsonProperty("run_id") String run_id
) {
}
