// Generated by scripts/codegen.py; do not edit.
package com.keel.common.model;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import java.time.Instant;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SuspendEvent(
    @JsonProperty("run_id") String run_id,
    @JsonProperty("reason") SuspendEventReasonValue reason,
    @JsonProperty("ref") String ref,
    @JsonProperty("prompt") String prompt,
    @JsonSerialize(using = ToStringSerializer.class) @JsonProperty("deadline") Instant deadline,
    @JsonProperty("resume_token") String resume_token,
    @JsonProperty("trace_id") String trace_id
) {
    public enum SuspendEventReasonValue {
        APPROVAL("approval"), INPUT_REQUIRED("input_required"), HANDOFF("handoff");
        private final String value;
        SuspendEventReasonValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static SuspendEventReasonValue fromValue(String value) {
            for (SuspendEventReasonValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

}
