// Generated by scripts/codegen.py; do not edit.
package com.keel.common.model;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import java.time.Instant;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ToolEvent(
    @JsonProperty("name") String name,
    @JsonProperty("status") ToolEventStatusValue status
) {
    public enum ToolEventStatusValue {
        OK("ok"), FALLBACK("fallback"), FAILED("failed");
        private final String value;
        ToolEventStatusValue(String value) { this.value = value; }
        @JsonValue public String value() { return value; }
        @JsonCreator public static ToolEventStatusValue fromValue(String value) {
            for (ToolEventStatusValue item : values()) if (item.value.equals(value)) return item;
            throw new IllegalArgumentException("Unknown enum value: " + value);
        }
    }

}
