/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前用户与可见范围
         * @description 前端据此控制菜单和按钮可见性；后端每个接口仍要再校验一次。
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insight/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 总览页全部数据
         * @description 一次返回页面所需的全部内容，前端不做二次聚合。
         */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 智能体列表 */
        get: operations["listAgents"];
        put?: never;
        /** 注册智能体（keel register / 新建向导第四步） */
        post: operations["registerAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["AgentName"];
            };
            cookie?: never;
        };
        /** 智能体详情（抽屉） */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{name}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["AgentName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 向已注册的智能体发一轮对话 */
        post: operations["chatWithAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{name}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["AgentName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发布（必须携带已通过的 gateRunId） */
        post: operations["releaseAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{name}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["AgentName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 下线（吊销虚拟 Key、删 Secret、状态置 RETIRED） */
        post: operations["retireAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/name-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 新建向导第二步：名称可用性校验 */
        get: operations["checkAgentName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/manifest-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新建向导第四步：由表单生成 agent.yaml 预览 */
        post: operations["previewManifest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 新建向导用的字典（模板、可选工具、知识库、模型、组织） */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insight/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 共享服务页全部数据
         * @description 服务健康来自 K8s 探测，指标来自 Prometheus，知识库来自 rag-forge。调用方和模型成本按环境过滤。知识库没有环境字段，不按环境拆开。
         */
        get: operations["getSharedServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insight/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * trace 列表
         * @description 原型里这一块是写死的五条「最近调用」，正式实现必须是真列表：
         *     可按智能体筛选、可分页、可按状态过滤。
         */
        get: operations["listTraces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insight/traces/{traceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                traceId: string;
            };
            cookie?: never;
        };
        /**
         * trace 详情
         * @description keel-server 调 Langfuse Observations API v2 取全部节点后组装，
         *     再叠加 keel-audit 的审计事件和 keel-server 的审批记录。
         *     协作图、泳道时间线、调用树三种视图共用这一份 nodes 数据，前端不再二次请求。
         */
        get: operations["getTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/{agent}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent: string;
            };
            cookie?: never;
        };
        /** 最近一次门禁结论与分维度对比 */
        get: operations["getLatestEval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/{agent}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动运行一次回归 */
        post: operations["runEval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        /** 回归进度 */
        get: operations["getEvalRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工具注册表 */
        get: operations["listTools"];
        put?: never;
        /** 注册 MCP 工具 */
        post: operations["registerTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        /** 工具详情（抽屉）：策略、依赖方、版本历史 */
        get: operations["getTool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/{name}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 发布新版本
         * @description 描述或参数变化会触发所有依赖方回归评测。
         *     破坏兼容必须用新名字（如 work_order_create.v2），不能在原名上发版。
         */
        post: operations["publishToolVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/{name}/deprecate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 废弃（必须给替代工具和截止日期） */
        post: operations["deprecateTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/{name}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 下线
         * @description 有 prod 依赖方时返回 409，只能先废弃。
         */
        post: operations["retireTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/{name}/dependents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        /** 依赖方（manifest 声明 + 30 天调用量） */
        get: operations["listToolDependents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 审批单列表
         * @description 审批人只看得到分给自己的单子，由后端按当前用户过滤。
         */
        get: operations["listApprovals"];
        put?: never;
        /**
         * 发起审批单
         * @description 导出、工具变更、智能体配置与下线都从这里建单。runId 非空时必须已经有对应的 agent_run。
         *     命中策略冷却期时不新建单，直接返回上一张 APPROVED。
         */
        post: operations["openApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批准 / 驳回 */
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 挂起等人回话的执行
         * @description 只返回 status=SUSPENDED 且 reason 为 input_required / handoff 的 run；reason=approval 的在 /approvals 里。
         */
        get: operations["listSuspendedRuns"];
        put?: never;
        /**
         * 登记一次等人回话的挂起
         * @description reason 只接受 input_required 或 handoff。同一个 runId 再次登记且仍是同一挂起原因时返回原记录。
         */
        post: operations["openSuspendedRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/input": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 回复挂起的执行。keel-server 据此调智能体的 /v1/runs/{id}/resume */
        post: operations["answerSuspendedRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审计事件查询 */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动触发哈希链校验 */
        post: operations["verifyAuditChain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 申请导出（自动建审批单，批准后才生成脱敏文件） */
        post: operations["requestAuditExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insight/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 模型网关页全部数据
         * @description 模型与花费来自薄网关（人民币），单次调用明细在链路追踪页看（来自 Langfuse）。
         */
        get: operations["getModelGateway"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insight/costs/keys/{alias}/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 调整虚拟 Key 的人民币日预算
         * @description 保存后写到薄网关这把虚拟 Key，并记一条 config.change 审计。日预算与控制台滑杆一致，¥10 到 ¥200，步长 ¥5。
         */
        post: operations["updateModelBudget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            /**
             * @description 成功固定为 OK，失败为 contracts/error-codes.yaml 里的错误码
             * @example OK
             */
            code: string;
            message?: string | null;
            traceId: string;
            data?: unknown;
        };
        ApiError: {
            /** @example TOOL_NOT_GRANTED */
            code: string;
            message: string;
            traceId: string;
            retryable: boolean;
        };
        PageMeta: {
            page: number;
            size: number;
            total: number;
        };
        /** @enum {string} */
        EnvName: "dev" | "test" | "staging" | "prod";
        /** @enum {string} */
        Risk: "LOW" | "MID" | "HIGH";
        /**
         * @description DRAFT 表示 keel new 预占了名称但还没 register。
         *     原型里的「门禁未过」不是独立状态，由 status=REGISTERED 且 gatePassed=false 推导。
         * @enum {string}
         */
        AgentStatus: "DRAFT" | "REGISTERED" | "ONLINE" | "DEGRADED" | "OFFLINE" | "RETIRED";
        /**
         * @description 三档口径，来自 askdb trace.py。degraded 归入 fallback，不单列。
         * @enum {string}
         */
        NodeStatus: "ok" | "fallback" | "failed";
        /**
         * @description 与 langfuse.observation.type 一致
         * @enum {string}
         */
        ObservationType: "agent" | "generation" | "tool" | "retriever" | "guardrail" | "event";
        /** @enum {string} */
        ToolStatus: "REGISTERED" | "ONLINE" | "DEPRECATED" | "RETIRED";
        /** @enum {string} */
        ToolAccess: "READ" | "WRITE" | "EXEC";
        /** @enum {string} */
        ToolScope: "PRIVATE" | "SHARED";
        /** @enum {string} */
        ApprovalStatus: "PENDING" | "APPROVED" | "REJECTED" | "EXPIRED";
        /**
         * @description 与 contracts/audit-event.schema.json 的 action 枚举完全一致，两边必须同时改。
         * @enum {string}
         */
        AuditAction: "invoke" | "tool.call" | "sql.execute" | "approval" | "config.change" | "data.export" | "run.suspend" | "run.resume" | "agent.register" | "release.gate";
        /** @enum {string} */
        AuditDecision: "allowed" | "denied" | "pending" | "approved" | "rejected";
        CurrentUser: {
            /** @example u_88 */
            userId?: string;
            /** @example amy */
            displayName?: string;
            /** @example 研发效能组 */
            org?: string;
            /** @enum {string} */
            platformRole?: "ADMIN" | "OWNER" | "APPROVER" | "VIEWER";
            /** @description auth-gateway 的 roles 多值 claim（P0-5 新增） */
            roles?: string[];
            /** @description 空数组表示可见全部 */
            visibleAgents?: string[];
            pendingApprovals?: number;
        };
        Overview: {
            kpi?: components["schemas"]["OverviewKpi"];
            agents?: components["schemas"]["AgentSummary"][];
            alerts?: components["schemas"]["Alert"][];
            costByAgent?: {
                agent?: string;
                /** Format: float */
                costCny?: number;
                /** Format: float */
                dailyBudgetCny?: number;
            }[];
        };
        OverviewKpi: {
            /** @example 7 */
            onlineAgents?: number;
            /** @example 10 */
            totalAgents?: number;
            /** @example 5 */
            bizCount?: number;
            /** @example 5 */
            devCount?: number;
            /** @example 13195 */
            calls?: number;
            /**
             * Format: float
             * @example 8.2
             */
            callsTrendPct?: number;
            /**
             * Format: float
             * @example 101.1
             */
            modelCostCny?: number;
            /**
             * Format: float
             * @example 0.86
             */
            avgScore?: number;
            /**
             * Format: float
             * @example 0.85
             */
            gateThreshold?: number;
            /** @example 3 */
            pendingApprovals?: number;
        };
        Alert: {
            /** Format: date-time */
            at?: string;
            /** @enum {string} */
            level?: "INFO" | "WARN" | "ERROR";
            agent?: string | null;
            /**
             * @description 对账 finding 或运行告警
             * @enum {string}
             */
            kind?: "OFFLINE" | "UNREGISTERED" | "ZOMBIE" | "RETIRE_INCOMPLETE" | "VERSION_MISMATCH" | "BUDGET_WARN" | "GATE_FAILED" | "PROMPT_DRIFT";
            text?: string;
            link?: string | null;
        };
        AgentSummary: {
            /** @example offshore-wind */
            name?: string;
            /** @example 风机维检 */
            displayName?: string;
            /** @enum {string} */
            category?: "biz" | "dev";
            /** @example Python */
            language?: string;
            /** @enum {string} */
            runtime?: "code" | "dify";
            /** @example graph-agent */
            template?: string;
            env?: components["schemas"]["EnvName"];
            /** @example v0.7.2 */
            version?: string;
            status?: components["schemas"]["AgentStatus"];
            /** @example 0/1 就绪 · CrashLoop */
            statusNote?: string | null;
            gatePassed?: boolean | null;
            ownerOrg?: string;
            ownerUser?: string;
            calls24h?: number;
            callsTotal?: number;
            /** Format: float */
            p95Seconds?: number;
            /** Format: float */
            costCny?: number;
            /** Format: float */
            dailyBudgetCny?: number;
            /** Format: float */
            score?: number | null;
            /**
             * @description 就绪/期望；Dify 为探活结果
             * @example 2/2
             */
            instances?: string;
            multiAgent?: boolean;
            /** @description spec.delegates 的个数，列表卡片用来显示「编排 N 个」 */
            delegateCount?: number;
        };
        AgentDetail: components["schemas"]["AgentSummary"] & {
            manifestYaml?: string;
            manifestHash?: string;
            knowledgeBases?: string[];
            tools?: string[];
            models?: string[];
            delegates?: string[];
            selfCheck?: components["schemas"]["SelfCheckReport"];
            instanceList?: {
                instanceId?: string;
                /** @enum {string} */
                source?: "k8s" | "heartbeat" | "probe";
                version?: string;
                ready?: boolean;
                /** Format: date-time */
                lastSeenAt?: string;
            }[];
            /** @description 替它开通的外部资源，下线时按此回收 */
            resources?: {
                /**
                 * @description litellm_key 是历史枚举值，语义为薄网关虚拟 Key
                 * @enum {string}
                 */
                type?: "litellm_key" | "langfuse" | "secret" | "dataset" | "oauth_client";
                externalId?: string;
                status?: string;
            }[];
            versions?: components["schemas"]["ReleaseRecord"][];
            /** @description 对账发现的问题 */
            findings?: components["schemas"]["Alert"][];
        };
        SelfCheckReport: {
            passed?: boolean;
            items?: {
                /** @example 高风险工具绑定审批策略 */
                name?: string;
                passed?: boolean;
                detail?: string | null;
            }[];
        };
        ReleaseRecord: {
            version?: string;
            env?: components["schemas"]["EnvName"];
            gatePassed?: boolean;
            /** Format: float */
            scoreTotal?: number | null;
            scoreByTag?: {
                [key: string]: number;
            };
            image?: string | null;
            ciRunUrl?: string | null;
            releasedBy?: string;
            /** Format: date-time */
            releasedAt?: string;
        };
        /** @description 向导表单；后端据此生成 agent.yaml。字段与 manifest.schema.json 一一对应。 */
        RegisterRequest: {
            name: string;
            displayName?: string;
            /** @enum {string} */
            category?: "biz" | "dev";
            ownerOrg?: string;
            ownerUser?: string;
            env: components["schemas"]["EnvName"];
            /** @enum {string} */
            runtime?: "code" | "dify";
            language?: string;
            template?: string;
            endpoint?: string;
            models?: {
                default?: string;
                fallback?: string[];
                /** Format: float */
                dailyBudgetCny?: number;
                maxSteps?: number;
            };
            knowledgeBases?: string[];
            tools?: string[];
            delegates?: string[];
            approvalPolicyId?: string | null;
        };
        Catalog: {
            templates?: {
                /** @example graph-agent */
                id?: string;
                /** @example 多步推理 */
                name?: string;
                description?: string;
                language?: string;
            }[];
            tools?: components["schemas"]["ToolSummary"][];
            knowledgeBases?: {
                kb?: string;
                owner?: string;
            }[];
            models?: string[];
            orgs?: string[];
            approvalPolicies?: {
                id?: string;
                /** @example 班组长审批 */
                name?: string;
            }[];
        };
        SharedServices: {
            services?: {
                /** @example rag-forge */
                name?: string;
                /** @example 知识检索 */
                role?: string;
                /** @example 2/2 · worker 1 */
                instances?: string;
                /** @example 0.78s */
                p95?: string | null;
                /** @example 0.6%（429） */
                errorRate?: string;
                /** @enum {string} */
                status?: "ONLINE" | "DEGRADED" | "OFFLINE";
            }[];
            ragforge?: {
                kpi?: {
                    searches24h?: number;
                    /** Format: float */
                    searchTrendPct?: number;
                    /** Format: float */
                    p95Seconds?: number;
                    /** Format: float */
                    p50Seconds?: number;
                    /** Format: float */
                    throttleRate?: number;
                    kbCount?: number;
                    staleKbCount?: number;
                    /** Format: float */
                    modelCostCny?: number;
                };
                /** @description 分段耗时。有直方图分位时用 p50Ms；现网只有 sum/count 时用 meanMs。 */
                stageLatency?: {
                    /** @enum {string} */
                    stage?: "rewrite" | "vector" | "keyword" | "rerank" | "other";
                    p50Ms?: number;
                    meanMs?: number;
                    /** @enum {string} */
                    basis?: "p50" | "mean";
                }[];
                callers?: {
                    agent?: string;
                    calls?: number;
                }[];
                knowledgeBases?: {
                    kb?: string;
                    owner?: string;
                    documents?: number;
                    /** Format: date-time */
                    updatedAt?: string;
                    searches24h?: number;
                    /** Format: float */
                    zeroHitRate?: number;
                    /** Format: float */
                    recallAt5?: number;
                    /** @description 超过 30 天未更新 */
                    stale?: boolean;
                }[];
            };
        };
        TraceSummary: {
            /** @example tr_8a31f0c2 */
            traceId?: string;
            question?: string;
            /** Format: date-time */
            startedAt?: string;
            sessionId?: string;
            turn?: number;
            userId?: string;
            userRole?: string | null;
            env?: components["schemas"]["EnvName"];
            rootAgent?: string;
            agents?: string[];
            multiAgent?: boolean;
            /** @description 智能体耗时，不含人工等待 */
            durationMs?: number;
            humanWaitMs?: number | null;
            tokens?: number;
            /** Format: float */
            costCny?: number;
            status?: components["schemas"]["NodeStatus"];
            /** @description 被护栏或准入拦截 */
            blocked?: boolean;
            cached?: boolean;
        };
        TraceDetail: {
            summary?: components["schemas"]["TraceSummary"];
            /** @description 深链 {langfuse}/project/{id}/traces/{traceId} */
            langfuseUrl?: string;
            /** @description 参与方，决定协作图与图例的配色 */
            agents?: {
                /** @example wind */
                key?: string;
                /** @example offshore-wind */
                name?: string;
                /** @example 子智能体 · 跨服务 */
                subtitle?: string;
                /** @example #2ec4b6 */
                color?: string;
                /** @enum {string} */
                kind?: "platform" | "supervisor" | "sub" | "service" | "human";
            }[];
            /** @description 关键路径构成，各项之和等于 durationMs */
            latencyBreakdown?: {
                /** @example offshore-wind */
                label?: string;
                ms?: number;
                agentKey?: string;
            }[];
            costBreakdown?: {
                agentKey?: string;
                /** Format: float */
                costCny?: number;
            }[];
            nodes?: components["schemas"]["TraceNode"][];
            /** @description 协作图连线；泳道视图用它画交接点 */
            edges?: {
                /** @description 节点 id */
                from?: string;
                to?: string;
                /** @example 委派 ① */
                label?: string | null;
                atMs?: number | null;
                parallel?: boolean;
            }[];
        };
        TraceNode: {
            id?: string;
            agentKey?: string;
            type?: components["schemas"]["ObservationType"];
            /** @example rag.fault-manual */
            name?: string;
            /** @example 检索手册 */
            shortName?: string | null;
            /** @example rag-forge */
            service?: string;
            /** @description 相对 trace 起点 */
            startMs?: number;
            durationMs?: number;
            /** @example 4m12s */
            humanWaitLabel?: string | null;
            status?: components["schemas"]["NodeStatus"];
            depth?: number;
            criticalPath?: boolean;
            /** @description agent 节点，耗时与成本含子节点 */
            aggregated?: boolean;
            model?: string | null;
            fallbackFrom?: string | null;
            llmKeyAlias?: string | null;
            tokensIn?: number | null;
            tokensOut?: number | null;
            tokens?: number | null;
            /** Format: float */
            costCny?: number | null;
            /** @description Langfuse observation 的 input，没有时用节点名 */
            inputSummary?: string;
            /** @description Langfuse observation 的 output，没有时用节点名 */
            outputSummary?: string;
            auditIds?: string[];
            approvalId?: string | null;
            /** @example 评测：askdb v1.9.0 门禁 0.88 通过 */
            gateNote?: string | null;
            deprecatedTool?: boolean;
        };
        EvalResult: {
            agent?: string;
            /** @example offshore-wind/inspection */
            dataset?: string;
            caseCount?: number;
            prodVersion?: string;
            candidateVersion?: string;
            /** Format: float */
            scoreTotal?: number;
            passed?: boolean;
            gate?: {
                /** Format: float */
                minScore?: number;
                /** Format: float */
                maxRegression?: number;
                byTag?: boolean;
            };
            /** @example 「安全规程合规」下降 6pt */
            reason?: string | null;
            /** Format: date-time */
            ranAt?: string;
            dimensions?: {
                /** @example 安全规程合规 */
                tag?: string;
                cases?: number;
                /** Format: float */
                prodScore?: number;
                /** Format: float */
                candidateScore?: number;
                /** Format: float */
                deltaPt?: number;
                /** @enum {string} */
                verdict?: "IMPROVED" | "TOLERATED" | "EXCEEDED";
            }[];
            newFailures?: {
                caseId?: string;
                input?: string;
                tags?: string[];
                reason?: string;
            }[];
        };
        ToolSummary: {
            /** @example work_order_create */
            name?: string;
            description?: string;
            scope?: components["schemas"]["ToolScope"];
            ownerAgent?: string | null;
            ownerOrg?: string | null;
            access?: components["schemas"]["ToolAccess"];
            risk?: components["schemas"]["Risk"];
            version?: string;
            status?: components["schemas"]["ToolStatus"];
            /** @example 班组长审批 */
            approvalPolicy?: string | null;
            calls24h?: number;
            dependentCount?: number;
            replacedBy?: string | null;
            /** Format: date */
            deprecateDeadline?: string | null;
        };
        ToolDetail: components["schemas"]["ToolSummary"] & {
            /** @description MCP 服务地址 */
            provider?: string | null;
            schemaJson?: {
                [key: string]: unknown;
            };
            dependents?: components["schemas"]["ToolDependent"][];
            versions?: {
                version?: string;
                change?: string;
                breaking?: boolean;
                /** Format: date-time */
                at?: string;
            }[];
        };
        ToolDependent: {
            agent?: string;
            env?: components["schemas"]["EnvName"];
            agentStatus?: components["schemas"]["AgentStatus"];
            declaredInManifest?: boolean;
            calls30d?: number;
        };
        ToolRegisterRequest: {
            name: string;
            description?: string;
            scope: components["schemas"]["ToolScope"];
            /** @description MCP 服务地址 */
            provider: string;
            access: components["schemas"]["ToolAccess"];
            risk: components["schemas"]["Risk"];
            approvalPolicyId?: string | null;
            schemaJson: {
                [key: string]: unknown;
            };
        };
        Approval: {
            /** @example ap_0912 */
            id?: string;
            /**
             * @description 草案（P3-1 定稿）。与 approval_request.subject_type 一致，见 docs/specs/p0/P0-1a-run-lifecycle.md
             * @enum {string}
             */
            subjectType?: "tool.call" | "tool.config" | "agent.config" | "agent.retire" | "data.export";
            /** @description 工具名 / 智能体名 / 导出申请 id */
            subjectRef?: string;
            /** @description 非空表示有一次执行正挂起等这张单 */
            runId?: string | null;
            /** @example 班组长审批 */
            policyName?: string | null;
            agent?: string;
            /** @description 仅 subjectType=tool.* 时有值；新代码用 subjectRef */
            tool?: string;
            risk?: components["schemas"]["Risk"];
            traceId?: string;
            actorUser?: string;
            /** @description 人可读的动作摘要；不含完整 payload，原文需另走审批接口 */
            summary?: string;
            payloadDigest?: string;
            status?: components["schemas"]["ApprovalStatus"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expiresAt?: string | null;
            decidedBy?: string | null;
            /** Format: date-time */
            decidedAt?: string | null;
        };
        /** @description 草案（P3-1 定稿）。挂起等人回话的执行，没有审批单；审批中心「人工介入」一组的数据来源 */
        SuspendedRun: {
            /** @example r_7b4a */
            runId?: string;
            agent?: string;
            env?: components["schemas"]["EnvName"];
            traceId?: string;
            /** @enum {string} */
            reason?: "input_required" | "handoff";
            /** @description 要问用户的话 / 交接说明 */
            prompt?: string;
            actorUser?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            deadline?: string | null;
        };
        /** @description 与 contracts/audit-event.schema.json 同构，额外带 hash、prevHash、hashVerified 供详情展示哈希链 */
        AuditEvent: {
            eventId?: string;
            /** Format: date-time */
            ts?: string;
            agent?: string;
            env?: components["schemas"]["EnvName"];
            traceId?: string | null;
            actor?: {
                userId?: string;
                orgId?: string | null;
                role?: string | null;
            };
            action?: components["schemas"]["AuditAction"];
            resource?: string;
            risk?: components["schemas"]["Risk"];
            decision?: components["schemas"]["AuditDecision"];
            approver?: string | null;
            /** @description 只含 manifest captureFields 白名单字段，已脱敏 */
            payload?: {
                [key: string]: unknown;
            };
            inputDigest?: string;
            hashVerified?: boolean;
            /** @description 本事件 sha256 hex */
            hash?: string;
            /** @description 同智能体链上一条的 hash，链头为空 */
            prevHash?: string | null;
        };
        ModelGateway: {
            models?: {
                /** @example qwen-plus */
                model?: string;
                /** @example DashScope */
                provider?: string;
                /** @example 主力 */
                role?: string;
                calls?: number;
                /**
                 * @description 窗口内延迟 P95，没有样本时为空
                 * @example 4.6s
                 */
                p95?: string;
                /**
                 * Format: float
                 * @description 窗口内超时次数 / 调用次数。没有延迟或超时样本时为空
                 */
                errorRate?: number;
                /** Format: float */
                costCny?: number;
                /** @enum {string} */
                status?: "ok" | "warn" | "bad";
                /** @description 薄网关是否为该模型配置了单价；为 false 时表示配置漂移 */
                priceConfigured?: boolean;
            }[];
            keys?: {
                /** @example offshore-wind-prod */
                alias?: string;
                agent?: string;
                env?: components["schemas"]["EnvName"];
                models?: string[];
                /** Format: float */
                dailyBudgetCny?: number;
                /** Format: float */
                spentCny?: number;
                /** @enum {string} */
                status?: "ACTIVE" | "BLOCKED";
            }[];
            /** @description 由各智能体 manifest 生成，写入薄网关的虚拟 Key */
            routing?: {
                agent?: string;
                default?: string;
                fallback?: string[];
                timeoutSeconds?: number;
            }[];
        };
    };
    responses: {
        /** @description 统一错误体 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        Env: "all" | "dev" | "test" | "staging" | "prod";
        Page: number;
        Size: 10 | 20 | 50 | 100;
        AgentName: string;
        ToolName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CurrentUser"];
                    };
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                range?: "24h" | "7d" | "30d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Overview"];
                    };
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                category?: "all" | "biz" | "dev";
                status?: components["schemas"]["AgentStatus"];
                /** @description 按 id、名称、负责人模糊匹配 */
                q?: string;
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["PageMeta"] & {
                            items?: components["schemas"]["AgentSummary"][];
                        };
                    };
                };
            };
        };
    };
    registerAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册完成，返回自检报告 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["SelfCheckReport"];
                    };
                };
            };
            409: components["responses"]["Error"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["AgentName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["AgentDetail"];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    chatWithAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["AgentName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            /** @description 智能体的最终回复 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            text?: string;
                            traceId?: string | null;
                        };
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    releaseAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["AgentName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    env: "staging" | "prod";
                    gateRunId: string;
                    image: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ReleaseRecord"];
                    };
                };
            };
            /** @description 门禁未通过，发布被拒 */
            412: components["responses"]["Error"];
        };
    };
    retireAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["AgentName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    env: components["schemas"]["EnvName"];
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    checkAgentName: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            available?: boolean;
                            /** @description 不可用时的原因，如「已被占用」「必须小写字母开头」 */
                            reason?: string | null;
                        };
                    };
                };
            };
        };
    };
    previewManifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            /** @description agent.yaml 全文 */
                            yaml?: string;
                            warnings?: string[];
                        };
                    };
                };
            };
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Catalog"];
                    };
                };
            };
        };
    };
    getSharedServices: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["SharedServices"];
                    };
                };
            };
        };
    };
    listTraces: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                /** @description 参与该 trace 的任一智能体，缺省为全部 */
                agent?: string;
                status?: components["schemas"]["NodeStatus"];
                minDurationMs?: number;
                from?: string;
                to?: string;
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["PageMeta"] & {
                            items?: components["schemas"]["TraceSummary"][];
                        };
                    };
                };
            };
        };
    };
    getTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                traceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TraceDetail"];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getLatestEval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["EvalResult"];
                    };
                };
            };
        };
    };
    runEval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已接受，异步执行 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            runId?: string;
                        };
                    };
                };
            };
        };
    };
    getEvalRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            runId?: string;
                            /** @enum {string} */
                            state?: "RUNNING" | "DONE" | "FAILED";
                            /**
                             * Format: float
                             * @description 0~1
                             */
                            progress?: number;
                            result?: components["schemas"]["EvalResult"] | null;
                        };
                    };
                };
            };
        };
    };
    listTools: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                scope?: "all" | "PRIVATE" | "SHARED";
                status?: components["schemas"]["ToolStatus"];
                risk?: components["schemas"]["Risk"];
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["PageMeta"] & {
                            items?: components["schemas"]["ToolSummary"][];
                        };
                    };
                };
            };
        };
    };
    registerTool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolRegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    getTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ToolDetail"];
                    };
                };
            };
        };
    };
    publishToolVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    version: string;
                    description?: string;
                    schemaJson: {
                        [key: string]: unknown;
                    };
                    access?: components["schemas"]["ToolAccess"];
                    risk?: components["schemas"]["Risk"];
                    breaking: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            /** @description 被触发回归评测的依赖方 */
                            triggeredRegressions?: string[];
                        };
                    };
                };
            };
            /** @description breaking=true 时必须改名 */
            400: components["responses"]["Error"];
        };
    };
    deprecateTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    replacedBy: string;
                    /** Format: date */
                    deadline: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    retireTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description 存在 prod 依赖，拒绝下线 */
            409: components["responses"]["Error"];
        };
    };
    listToolDependents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ToolDependent"][];
                    };
                };
            };
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                status?: components["schemas"]["ApprovalStatus"];
                agent?: string;
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["PageMeta"] & {
                            items?: components["schemas"]["Approval"][];
                        };
                    };
                };
            };
        };
    };
    openApproval: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    subjectType: "tool.call" | "tool.config" | "agent.config" | "agent.retire" | "data.export";
                    subjectRef: string;
                    summary: string;
                    actorUser: string;
                    agent?: string;
                    risk?: components["schemas"]["Risk"];
                    runId?: string | null;
                    traceId?: string;
                    payloadDigest?: string;
                    policyName?: string | null;
                    env?: components["schemas"]["EnvName"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Approval"];
                    };
                };
            };
            /** @description 参数不合法 */
            400: components["responses"]["Error"];
            /** @description 策略、智能体或 run 不存在 */
            404: components["responses"]["Error"];
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "APPROVE" | "REJECT";
                    comment?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Approval"];
                    };
                };
            };
            /** @description 单子已过期或已被处理 */
            409: components["responses"]["Error"];
        };
    };
    listSuspendedRuns: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                agent?: string;
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["PageMeta"] & {
                            items?: components["schemas"]["SuspendedRun"][];
                        };
                    };
                };
            };
        };
    };
    openSuspendedRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    runId: string;
                    agent: string;
                    env?: components["schemas"]["EnvName"];
                    traceId?: string;
                    /** @enum {string} */
                    reason: "input_required" | "handoff";
                    prompt: string;
                    actorUser: string;
                    /** Format: date-time */
                    deadline?: string | null;
                    checkpointRef?: string | null;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["SuspendedRun"];
                    };
                };
            };
            /** @description 参数不合法 */
            400: components["responses"]["Error"];
            /** @description 智能体不存在 */
            404: components["responses"]["Error"];
            /** @description runId 已存在且不能再次挂起 */
            409: components["responses"]["Error"];
        };
    };
    answerSuspendedRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description 执行已不处于可恢复状态（RUN_NOT_RESUMABLE / RUN_EXPIRED） */
            409: components["responses"]["Error"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                agent?: string;
                risk?: components["schemas"]["Risk"];
                action?: components["schemas"]["AuditAction"];
                decision?: components["schemas"]["AuditDecision"];
                traceId?: string;
                from?: string;
                to?: string;
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["PageMeta"] & {
                            items?: components["schemas"]["AuditEvent"][];
                        };
                    };
                };
            };
        };
    };
    verifyAuditChain: {
        parameters: {
            query?: {
                agent?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            /** @description 校验条数 */
                            checked?: number;
                            intact?: boolean;
                            /** @description 断链处的 eventId */
                            brokenAt?: string | null;
                            elapsedMs?: number;
                        };
                    };
                };
            };
        };
    };
    requestAuditExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 与 /audit/events 相同的筛选条件 */
                    filter: {
                        [key: string]: unknown;
                    };
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description 已建审批单 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            exportId?: string;
                            approvalId?: string;
                        };
                    };
                };
            };
        };
    };
    getModelGateway: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                range?: "24h" | "7d" | "30d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ModelGateway"];
                    };
                };
            };
        };
    };
    updateModelBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alias: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: float */
                    dailyBudgetCny: number;
                };
            };
        };
        responses: {
            /** @description 已写到薄网关 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            alias?: string;
                            /** Format: float */
                            dailyBudgetCny?: number;
                        };
                    };
                };
            };
        };
    };
}
