// Generated by scripts/codegen.py; do not edit.
package com.keel.common.error;

public enum ErrorCode {
    SERVER_INVALID_PARAM("请求参数不合法", false, 400),
    SERVER_NOT_FOUND("资源不存在", false, 404),
    SERVER_INTERNAL_ERROR("服务内部错误", true, 500),
    AGENT_MANIFEST_INVALID("manifest 未通过校验", false, 400),
    AGENT_SELF_CHECK_FAILED("注册自检未通过", false, 409),
    AGENT_NAME_TAKEN("名称已被占用", false, 409),
    AGENT_NOT_RETIRED("智能体还没下线，不能删除", false, 409),
    GW_QUOTA_EXCEEDED("配额已用完", true, 429),
    GW_CONCURRENCY_LIMIT("并发连接数达到上限", true, 429),
    GW_AGENT_OFFLINE("智能体当前不可用", true, 503),
    TOOL_NOT_GRANTED("智能体没有该工具的使用授权", false, 403),
    TOOL_RETIRED("工具已下线", false, 410),
    TOOL_TIMEOUT("工具调用超时", true, 504),
    TOOL_HAS_PROD_DEPENDENTS("工具仍有 prod 依赖方，不能直接下线", false, 409),
    APPROVAL_REJECTED("审批被驳回", false, 403),
    APPROVAL_EXPIRED("审批超时未处理", false, 408),
    RUN_NOT_FOUND("找不到该次执行", false, 404),
    RUN_NOT_RESUMABLE("该次执行不处于可恢复状态", false, 409),
    RUN_EXPIRED("该次执行已超过截止时间", false, 410),
    RUN_RESUME_DENIED("无法恢复执行，凭据已失效", false, 401),
    AUDIT_WRITE_FAILED("审计写入失败，操作已拒绝", true, 503),
    GUARD_INJECTION_BLOCKED("输入被提示词注入检测拦截", false, 400),
    LLM_BUDGET_EXCEEDED("模型日预算已用完", true, 429),
    LLM_KEY_BLOCKED("虚拟 Key 已停用", false, 401),
    DELEGATE_NOT_DECLARED("目标智能体未在 manifest 的 delegates 中声明", false, 403),
    PROMPT_NOT_DECLARED("提示词未在 manifest 中声明", false, 404),
    PROMPT_UNAVAILABLE("当前环境的提示词不可用", true, 503),
    PROMPT_VARIABLE_MISSING("提示词变量缺失", false, 400),
    PROMPT_TYPE_MISMATCH("提示词类型与声明不一致", false, 400),
    PROMPT_NOT_GATED("提示词尚未通过 staging 回归，不能发布", false, 409),
    PROMPT_ROLLBACK_TARGET("只能回滚到发布过的提示词版本", false, 409),
    AUTH_UNAUTHENTICATED("请先登录后再继续", false, 401),
    AUTH_TOKEN_EXPIRED("登录已过期，请重新登录", true, 401),
    AUTH_TOKEN_AUDIENCE("这个登录态不能用于 Keel 控制台", false, 401),
    AUTH_CONSOLE_FORBIDDEN("这个账号还没有开通控制台，请联系平台管理员", false, 403),
    AUTH_PREVIEW_READONLY("预览模式只能查看，登录后才能操作", false, 403),
    AUTH_BAD_CREDENTIALS("账号或密码不正确。没有账号或忘记密码，请联系平台管理员", false, 401),
    AUTH_CAPTCHA_REQUIRED("为了保护账号，请填写图形验证码后再登录", false, 423),
    AUTH_LOCKED("登录失败次数过多，请 15 分钟后再试", false, 423),
    AUTH_SMS_RATE_LIMITED("操作太频繁，请稍后再试", true, 429),
    AUTH_GATEWAY_UNAVAILABLE("登录服务暂时不可用，请稍后再试", true, 503),
    GIT_UPSTREAM_FAILED("GitHub 调用失败", true, 502),
    DEVFLOW_BUDGET_EXCEEDED("研发任务花费已达到预算上限", false, 409),
    DEVFLOW_FIX_ROUNDS_EXHAUSTED("修复轮次已用完", false, 409),
    DEVFLOW_HOLDOUT_FAILED("隐藏考题未通过门禁", false, 409),
    DEVFLOW_SANDBOX_TIMEOUT("沙箱执行超过 10 分钟", true, 504),
    DEVFLOW_GRANT_MISSING("缺少共享工具授权", false, 403),
    DEVFLOW_LINEAGE_FORBIDDEN("不能向上生产，也不能修改自己", false, 403);
    private final String message;
    private final boolean retryable;
    private final int http;
    ErrorCode(String message, boolean retryable, int http) {
        this.message = message; this.retryable = retryable; this.http = http;
    }
    public String message() { return message; }
    public boolean retryable() { return retryable; }
    public int http() { return http; }
}
