// Generated by scripts/codegen.py; do not edit.
package com.keel.common.error;

public enum ErrorCode {
    SERVER_INVALID_PARAM("请求参数不合法", false, 400),
    SERVER_NOT_FOUND("资源不存在", false, 404),
    SERVER_INTERNAL_ERROR("服务内部错误", true, 500),
    AGENT_MANIFEST_INVALID("manifest 未通过校验", false, 400),
    AGENT_SELF_CHECK_FAILED("注册自检未通过", false, 409),
    AGENT_NAME_TAKEN("名称已被占用", false, 409),
    GW_QUOTA_EXCEEDED("配额已用完", true, 429),
    GW_CONCURRENCY_LIMIT("并发连接数达到上限", true, 429),
    GW_AGENT_OFFLINE("智能体当前不可用", true, 503),
    TOOL_NOT_GRANTED("智能体没有该工具的使用授权", false, 403),
    TOOL_RETIRED("工具已下线", false, 410),
    TOOL_TIMEOUT("工具调用超时", true, 504),
    TOOL_HAS_PROD_DEPENDENTS("工具仍有 prod 依赖方，不能直接下线", false, 409),
    APPROVAL_REJECTED("审批被驳回", false, 403),
    APPROVAL_EXPIRED("审批超时未处理", false, 408),
    RUN_NOT_FOUND("找不到该次执行", false, 404),
    RUN_NOT_RESUMABLE("该次执行不处于可恢复状态", false, 409),
    RUN_EXPIRED("该次执行已超过截止时间", false, 410),
    RUN_RESUME_DENIED("无法恢复执行，凭据已失效", false, 401),
    AUDIT_WRITE_FAILED("审计写入失败，操作已拒绝", true, 503),
    GUARD_INJECTION_BLOCKED("输入被提示词注入检测拦截", false, 400),
    DELEGATE_NOT_DECLARED("目标智能体未在 manifest 的 delegates 中声明", false, 403);
    private final String message;
    private final boolean retryable;
    private final int http;
    ErrorCode(String message, boolean retryable, int http) {
        this.message = message; this.retryable = retryable; this.http = http;
    }
    public String message() { return message; }
    public boolean retryable() { return retryable; }
    public int http() { return http; }
}
