#!/usr/bin/env python3
"""Generate Java and Pydantic v2 models from the frozen keel/v1 schemas."""
from __future__ import annotations

import json
import keyword
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
JAVA = ROOT / "keel-common/src/main/java/com/keel/common"
PYTHON = ROOT / "sdk-python/keel/_generated"


def load(name):
    return json.loads((CONTRACTS / name).read_text(encoding="utf-8"))


def merge(left, right):
    result = dict(left)
    for key, value in right.items():
        if key == "properties" and key in result:
            props = dict(result[key])
            for name, prop in value.items():
                props[name] = merge(props[name], prop) if name in props else prop
            result[key] = props
        elif key == "required" and key in result:
            result[key] = list(dict.fromkeys(result[key] + value))
        else:
            result[key] = value
    return result


def resolve(node, root):
    node = dict(node)
    if "$ref" in node:
        pointer = node.pop("$ref")
        assert pointer.startswith("#/")
        target = root
        for segment in pointer[2:].split("/"):
            target = target[segment]
        node = merge(resolve(target, root), node)
    if "allOf" in node:
        for part in node.pop("allOf"):
            if "$ref" in part or "properties" in part:
                node = merge(node, resolve(part, root))
    return node


def schema(name):
    root = load(name)
    if name == "manifest.schema.json":
        # Conditional agent/service spec fields share one wire-level spec object.
        spec = root["properties"]["spec"]
        for variant in ("agentSpec", "serviceSpec"):
            spec = merge(spec, root["$defs"][variant])
        root["properties"]["spec"] = spec
    return root


def pascal(value):
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^a-zA-Z0-9]+", value) if part)


def enum_name(value):
    return re.sub(r"[^A-Z0-9]+", "_", value.upper()).strip("_")


def field_name(value):
    return value + "_" if keyword.iskeyword(value) or value in {"default", "record", "yield"} else value


def java_string(value):
    return json.dumps(value, ensure_ascii=False)


def java_model(name, root, event_defs=False):
    if event_defs:
        for event in ("step", "tool", "token", "final", "error", "suspend"):
            java_model(pascal(event) + "Event", merge(root, root["$defs"][event]))
        return
    lines = ["// Generated by scripts/codegen.py; do not edit.", "package com.keel.common.model;", "",
             "import com.fasterxml.jackson.annotation.*;", "import com.fasterxml.jackson.databind.annotation.JsonSerialize;",
             "import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;", "import java.time.Instant;", "import java.util.List;", "import java.util.Map;", "",
             f"public final class {name} {{", f"    private {name}() {{}}", ""]
    classes = {}
    enums = {}

    def typ(node, path):
        node = resolve(node, root)
        if "enum" in node or "const" in node:
            values = node.get("enum", [node.get("const")])
            key = pascal(path) + "Value"
            enums[key] = values
            return key
        kind = node.get("type", "object" if "properties" in node else None)
        if kind == "string":
            return "Instant" if node.get("format") == "date-time" else "String"
        if kind == "integer":
            return "Integer"
        if kind == "number":
            return "Double"
        if kind == "boolean":
            return "Boolean"
        if kind == "array":
            return f"List<{typ(node['items'], path + 'Item')}>"
        if kind == "object":
            if not node.get("properties"):
                return "Map<String, Object>"
            key = pascal(path)
            classes[key] = node
            return key
        raise ValueError(f"Unsupported schema at {path}: {node}")

    classes[name] = root
    emitted = set()
    while pending := [(key, value) for key, value in classes.items() if key not in emitted]:
        key, node = pending[0]
        emitted.add(key)
        node = resolve(node, root)
        fields = [(prop, typ(child, key + pascal(prop))) for prop, child in node.get("properties", {}).items()]
        lines.extend(["    @JsonIgnoreProperties(ignoreUnknown = true)", "    @JsonInclude(JsonInclude.Include.NON_NULL)",
                      f"    public record {key}("])
        lines.extend("        " + ("@JsonSerialize(using = ToStringSerializer.class) " if type_ == "Instant" else "") +
                     "@JsonProperty(" + java_string(prop) + ") " + type_ + " " + field_name(prop) +
                     ("," if i < len(fields) - 1 else "") for i, (prop, type_) in enumerate(fields))
        lines.extend(["    ) {}", ""])
    for key, values in enums.items():
        lines.append(f"    public enum {key} {{")
        lines.append("        " + ", ".join(f"{enum_name(value)}({java_string(value)})" for value in values) + ";")
        lines.extend(["        private final String value;", f"        {key}(String value) {{ this.value = value; }}",
                      "        @JsonValue public String value() { return value; }",
                      f"        @JsonCreator public static {key} fromValue(String value) {{",
                      f"            for ({key} item : values()) if (item.value.equals(value)) return item;",
                      "            throw new IllegalArgumentException(\"Unknown enum value: \" + value);", "        }", "    }", ""])
    lines.append("}")
    # Lift the main record out of the namespace shell; nested types remain inside it.
    start = lines.index("    @JsonIgnoreProperties(ignoreUnknown = true)")
    end = lines.index("    ) {}", start) + 1
    main = lines[start:end]
    del lines[start:end + 1]
    lines = lines[:lines.index(f"public final class {name} {{")] + [
        "@JsonIgnoreProperties(ignoreUnknown = true)", "@JsonInclude(JsonInclude.Include.NON_NULL)",
        f"public record {name}("
    ] + [line[4:] for line in main[3:-1]] + [") {", *lines[lines.index(f"public final class {name} {{") + 3:]]
    (JAVA / "model").mkdir(parents=True, exist_ok=True)
    (JAVA / "model" / f"{name}.java").write_text("\n".join(lines) + "\n", encoding="utf-8")


def python_model(filename, main, root, event_defs=False):
    lines = ["# Generated by scripts/codegen.py; do not edit.", "from __future__ import annotations", "",
             "from datetime import datetime, timezone", "from enum import Enum", "from typing import Any, Optional",
             "from pydantic import BaseModel, ConfigDict, Field, field_serializer, field_validator", "", "",
             "class KeelModel(BaseModel):", "    model_config = ConfigDict(extra='ignore')", "",
             "    def model_dump(self, **kwargs):", "        kwargs.setdefault('exclude_none', True)",
             "        kwargs.setdefault('by_alias', True)",
             "        return super().model_dump(**kwargs)", "", "    def model_dump_json(self, **kwargs):",
             "        kwargs.setdefault('exclude_none', True)", "        kwargs.setdefault('by_alias', True)",
             "        return super().model_dump_json(**kwargs)", ""]
    classes = {}
    enums = {}

    def typ(node, path):
        node = resolve(node, root)
        if "enum" in node or "const" in node:
            key = pascal(path) + "Value"
            enums[key] = node.get("enum", [node.get("const")])
            return key
        kind = node.get("type", "object" if "properties" in node else None)
        if kind == "string":
            return "datetime" if node.get("format") == "date-time" else "str"
        if kind == "integer":
            return "int"
        if kind == "number":
            return "float"
        if kind == "boolean":
            return "bool"
        if kind == "array":
            return f"list[{typ(node['items'], path + 'Item')}]"
        if kind == "object":
            if not node.get("properties"):
                return "dict[str, Any]"
            key = pascal(path)
            classes[key] = node
            return key
        raise ValueError(f"Unsupported schema at {path}: {node}")

    if event_defs:
        for event in ("step", "tool", "token", "final", "error", "suspend"):
            classes[pascal(event) + "Event"] = root["$defs"][event]
    else:
        classes[main] = root
    bodies = {}
    while pending := [(key, value) for key, value in classes.items() if key not in bodies]:
        key, node = pending[0]
        node = resolve(node, root)
        required = set(node.get("required", []))
        fields = []
        dates = []
        for prop, child in node.get("properties", {}).items():
            type_ = typ(child, key + pascal(prop))
            ident = field_name(prop)
            if ident != prop:
                fields.append(f"    {ident}: {type_} = Field(alias={prop!r})" if prop in required else
                              f"    {ident}: Optional[{type_}] = Field(default=None, alias={prop!r})")
            else:
                fields.append(f"    {ident}: {type_}" if prop in required else f"    {ident}: Optional[{type_}] = None")
            if resolve(child, root).get("format") == "date-time":
                dates.append(prop)
        if not fields:
            fields.append("    pass")
        for prop in dates:
            fields.extend(["", f"    @field_validator('{prop}')",
                           f"    @classmethod", f"    def validate_{prop}(cls, value: datetime | None):",
                           "        if value is not None and value.tzinfo is None:",
                           "            raise ValueError('RFC 3339 timestamp requires timezone')",
                           "        return value", "", f"    @field_serializer('{prop}', when_used='json')",
                           f"    def serialize_{prop}(self, value: datetime | None):",
                           "        if value is None:", "            return None",
                           "        if value.tzinfo is None:", "            raise ValueError('RFC 3339 timestamp requires timezone')",
                           "        return value.astimezone(timezone.utc).isoformat().replace('+00:00', 'Z')"])
        bodies[key] = fields
    for key, values in enums.items():
        lines.extend(["", f"class {key}(str, Enum):"])
        lines.extend(f"    {enum_name(value)} = {value!r}" for value in values)
        lines.append("")
    for key, fields in bodies.items():
        lines.extend(["", f"class {key}(KeelModel):", *fields, ""])
    lines.extend(["", "for _model in (" + ", ".join(bodies) + "):", "    _model.model_rebuild()"])
    PYTHON.mkdir(parents=True, exist_ok=True)
    (PYTHON / filename).write_text("\n".join(lines) + "\n", encoding="utf-8")


def error_codes():
    # The contract uses a simple codes: mapping; parse its indented entries without YAML dependencies.
    rows = []
    current = None
    for line in (CONTRACTS / "error-codes.yaml").read_text(encoding="utf-8").splitlines():
        if match := re.match(r"^  ([A-Z][A-Z0-9_]+):$", line):
            current = {"name": match.group(1)}
            rows.append(current)
        elif current is not None and (match := re.match(r"^    (message|retryable|http): (.+)$", line)):
            current[match.group(1)] = match.group(2)
    for row in rows:
        if set(row) != {"name", "message", "retryable", "http"}:
            raise ValueError(f"Incomplete error code: {row}")
    java = ["// Generated by scripts/codegen.py; do not edit.", "package com.keel.common.error;", "",
            "public enum ErrorCode {"]
    java.append("    " + ",\n    ".join(f"{r['name']}({java_string(r['message'])}, {r['retryable']}, {r['http']})" for r in rows) + ";")
    java.extend(["    private final String message;", "    private final boolean retryable;", "    private final int http;",
                 "    ErrorCode(String message, boolean retryable, int http) {",
                 "        this.message = message; this.retryable = retryable; this.http = http;", "    }",
                 "    public String message() { return message; }", "    public boolean retryable() { return retryable; }",
                 "    public int http() { return http; }", "}"])
    (JAVA / "error" / "ErrorCode.java").write_text("\n".join(java) + "\n", encoding="utf-8")
    py = ["# Generated by scripts/codegen.py; do not edit.", "from enum import Enum", "", "class ErrorCode(str, Enum):"]
    py.extend(f"    {r['name']} = {r['name']!r}" for r in rows)
    py.extend(["", "    @property", "    def retryable(self) -> bool:", "        return _DETAILS[self][1]",
               "", "    @property", "    def http(self) -> int:", "        return _DETAILS[self][2]",
               "", "    @property", "    def message(self) -> str:", "        return _DETAILS[self][0]", "", "_DETAILS = {"])
    py.extend(f"    ErrorCode.{r['name']}: ({r['message']!r}, {r['retryable'].title()}, {r['http']})," for r in rows)
    py.append("}")
    (PYTHON / "errors.py").write_text("\n".join(py) + "\n", encoding="utf-8")


def main():
    model_dir = JAVA / "model"
    model_dir.mkdir(parents=True, exist_ok=True)
    for path in model_dir.glob("*.java"):
        if path.read_text(encoding="utf-8").startswith("// Generated by scripts/codegen.py"):
            path.unlink()
    java_model("AgentManifest", schema("manifest.schema.json"))
    python_model("manifest.py", "AgentManifest", schema("manifest.schema.json"))
    java_model("SseEvents", schema("sse-events.schema.json"), True)
    python_model("events.py", "SseEvents", schema("sse-events.schema.json"), True)
    java_model("AuditEvent", schema("audit-event.schema.json"))
    python_model("audit.py", "AuditEvent", schema("audit-event.schema.json"))
    error_codes()
    (PYTHON / "__init__.py").write_text("# Generated models from keel/v1 contracts.\n", encoding="utf-8")


if __name__ == "__main__":
    main()
